(() => {
  'use strict';
  const chapters = window.ECON_CHAPTERS;
  const ids = Object.keys(chapters);
  const state = { chapter: new URLSearchParams(location.search).get('chapter') || 'ch03', page: 0, practice: 'quick', answers: {}, teacher: false };
  if (!chapters[state.chapter]) state.chapter = 'ch03';
  const $ = (s) => document.querySelector(s);
  const dom = {tabs:$('#chapterTabs'), type:$('#chapterType'), number:$('#chapterNumber'), title:$('#chapterTitle'), subtitle:$('#chapterSubtitle'), hook:$('#chapterHook'), pageMap:$('#pageMap'), spreads:$('#spreads'), dots:$('#pageDots'), prev:$('#prevPage'), next:$('#nextPage'), modelTitle:$('#modelTitle'), modelIntro:$('#modelIntro'), modelVisual:$('#modelVisual'), modelControls:$('#modelControls'), practice:$('#practiceGrid'), dialog:$('#chapterDialog'), dialogList:$('#chapterDialogList')};
  let animationFrame = null; let animationDuration = 1; let currentAnimationTime = 0;

  function fmt(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`}
  function current(){return chapters[state.chapter]}
  function pageAnimationStart(page){return ({ch03:[0,190,255],ch04:[58,270,335],ch19:[62,205,330]}[state.chapter]||[0])[page]||0}
  function setTheme(){document.documentElement.style.setProperty('--chapter-accent',current().accent)}
  function renderTabs(){dom.tabs.innerHTML=ids.map(id=>`<button class="chapter-tab ${id===state.chapter?'active':''}" data-chapter="${id}">${chapters[id].number} ${chapters[id].title}</button>`).join('');dom.dialogList.innerHTML=ids.map(id=>`<button data-chapter="${id}" style="padding:16px;border-radius:14px;border:1px solid rgba(255,255,255,.12);background:${id===state.chapter?'rgba(95,226,189,.12)':'rgba(255,255,255,.04)'};color:white;text-align:left"><strong>${chapters[id].number} ${chapters[id].title}</strong><br><small style="color:#a8b6c5">${chapters[id].type}｜${chapters[id].subtitle}</small></button>`).join('');document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>switchChapter(b.dataset.chapter))}
  function switchChapter(id){state.chapter=id;state.page=0;state.practice='quick';state.answers={};try{history.replaceState(null,'',`?chapter=${id}`)}catch(_){/* standalone about:blank/data URL */}dom.dialog.close?.();renderAll()}
  function renderHero(){const c=current();dom.type.textContent=c.type;dom.number.textContent=c.number;dom.title.textContent=c.title;dom.subtitle.textContent=c.subtitle;dom.hook.textContent=c.hook}
  function renderMap(){const c=current();dom.pageMap.innerHTML=c.pages.map((p,i)=>`<button class="map-card ${i===state.page?'active':''}" data-page="${i}"><span>書頁 ${i+1}</span><strong>${p.title}</strong><small>${p.lead.slice(0,52)}…</small></button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=Number(b.dataset.page);renderBook()})}
  function spreadMarkup(p,i){const start=pageAnimationStart(i),player=i===state.page?`<div class="animation-frame"><iframe title="${current().title} 機制動畫" src="${current().animation}" data-start="${start}" loading="eager"></iframe><div class="anim-overlay"></div></div><div class="player-controls"><button data-player="toggle">播放／暫停</button><button data-player="restart">重播本段</button><input data-player="seek" type="range" min="0" max="${current().duration}" value="${start}" step=".1"><select data-player="rate"><option value=".75">0.75×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option></select><span class="time-readout" data-time>${fmt(start)} / ${fmt(current().duration)}</span></div>`:'';return `<section class="spread ${i===state.page?'active':''}" data-spread="${i}"><article class="reading"><span class="page-no">${current().number} · BOOK SPREAD ${String(i+1).padStart(2,'0')}</span><h2>${p.title}</h2><p class="lead">${p.lead}</p><div class="concept-list">${p.bullets.map((b,j)=>`<div><i>${j+1}</i><span>${b}</span></div>`).join('')}</div><div class="checkpoint"><span>讀到這裡，先做判斷</span><strong>${p.checkpoint}</strong></div></article><article class="visual-page">${player}<div class="inline-practice"><span>立即應用</span><strong>${p.checkpoint}</strong><div class="options">${inlineOptions(i).map((o,j)=>`<button data-inline="${i}-${j}">${o}</button>`).join('')}</div><div class="feedback" data-inline-feedback></div></div></article></section>`}
  function inlineOptions(page){const sets={ch03:[['放棄的 NT$540 打工所得','電影票價','所有未做事情的總和','讀書帶來的分數'],['資源未充分運用','不可達','一定公平','機會成本為零'],['小柏','小安','兩人相同','無法判斷']],ch04:[['需求增加','需求量增加','供給增加','短缺'],['短缺','過剩','需求曲線右移','供給曲線左移'],['可負擔與程序公平','一定消除短缺','一定提高效率','增加座位']],ch19:[['G','C','I','NX'],['SRAS 左移','AD 右移','SRAS 右移','AD 左移'],['加重通膨','立即增加潛在 GDP','立刻降低成本','沒有副作用']]};return sets[state.chapter][page]}
  function inlineCorrect(page){return {ch03:[0,0,0],ch04:[0,0,0],ch19:[0,0,0]}[state.chapter][page]}
  function renderBook(){const c=current();dom.spreads.innerHTML=c.pages.map(spreadMarkup).join('');dom.dots.innerHTML=c.pages.map((_,i)=>`<button class="${i===state.page?'active':''}" data-dot="${i}"></button>`).join('');dom.prev.disabled=state.page===0;dom.next.disabled=state.page===c.pages.length-1;dom.next.textContent=state.page===c.pages.length-1?'本章書頁完成':'下一頁 →';renderMap();bindPlayer();bindInline();document.querySelectorAll('[data-dot]').forEach(b=>b.onclick=()=>{state.page=Number(b.dataset.dot);renderBook()});window.scrollTo({top:document.querySelector('.book-shell').offsetTop-80,behavior:'smooth'})}
  function bindPlayer(){const active=document.querySelector('.spread.active');animationFrame=active?.querySelector('iframe');const seek=active?.querySelector('[data-player="seek"]');const readout=active?.querySelector('[data-time]');const start=Number(animationFrame?.dataset.start||0);animationFrame?.addEventListener('load',()=>animationFrame?.contentWindow.postMessage({type:'econ-animation-seek',time:start},'*'),{once:true});active?.querySelector('[data-player="toggle"]')?.addEventListener('click',()=>animationFrame?.contentWindow.postMessage({type:'econ-animation-toggle'},'*'));active?.querySelector('[data-player="restart"]')?.addEventListener('click',()=>{animationFrame?.contentWindow.postMessage({type:'econ-animation-seek',time:start},'*');animationFrame?.contentWindow.postMessage({type:'econ-animation-play'},'*')});seek?.addEventListener('input',e=>animationFrame?.contentWindow.postMessage({type:'econ-animation-seek',time:Number(e.target.value)},'*'));active?.querySelector('[data-player="rate"]')?.addEventListener('change',e=>animationFrame?.contentWindow.postMessage({type:'econ-animation-rate',rate:Number(e.target.value)},'*'));window.__activeSeek=seek;window.__activeReadout=readout}
  function bindInline(){document.querySelectorAll('[data-inline]').forEach(btn=>btn.onclick=()=>{const [page,opt]=btn.dataset.inline.split('-').map(Number);const correct=inlineCorrect(page);btn.parentElement.querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('correct',i===correct);b.classList.toggle('wrong',i===opt&&i!==correct)});const fb=btn.closest('.inline-practice').querySelector('[data-inline-feedback]');fb.classList.add('show');fb.textContent=opt===correct?'正確。現在請用一句話說明造成變化的「原因」。':'再看一次：先找最先改變的因素，再判斷點、線或總體曲線。'})}
  function renderModel(){if(state.chapter==='ch03')renderModel03();if(state.chapter==='ch04')renderModel04();if(state.chapter==='ch19')renderModel19()}
  function renderModel03(){dom.modelTitle.textContent='時間配置、機會成本與 PPF';dom.modelIntro.textContent='移動同一個時間配置滑桿，同時觀察成績、所得與機會成本。';dom.modelVisual.innerHTML='<svg viewBox="0 0 720 440"><line class="axis" x1="70" y1="35" x2="70" y2="380"/><line class="axis" x1="70" y1="380" x2="670" y2="380"/><path class="curve-a" d="M100 75 C260 90 430 200 630 350"/><circle class="point" id="m03dot" cx="340" cy="180" r="10"/><line class="guide" id="m03h"/><line class="guide" id="m03v"/><text class="chart-label" x="18" y="40">成績</text><text class="chart-label" x="550" y="425">每週所得</text></svg>';dom.modelControls.innerHTML='<div class="control-group"><label>投入打工的可配置時間 <output id="m03hours">20 小時</output></label><input id="m03slider" type="range" min="0" max="40" value="20"></div><div class="model-summary"><span>目前取捨</span><strong id="m03summary"></strong><p>沿 PPF 移動不是「變差」，而是在兩個有價值的目標間做選擇。</p></div>';const slider=$('#m03slider');const update=()=>{const h=Number(slider.value),income=1200+h*180,score=Math.round(95-.015*h*h-.15*h);$('#m03hours').textContent=h+' 小時';$('#m03summary').textContent=`預估成績 ${score} 分；所得 NT$${income.toLocaleString('zh-TW')}；再增加 1 小時打工的機會成本約 ${Math.max(0,Math.round(.03*h+.15))} 分。`;const cx=100+h/40*530,cy=75+(h/40)**1.7*275;$('#m03dot').setAttribute('cx',cx);$('#m03dot').setAttribute('cy',cy);$('#m03h').setAttribute('x1',70);$('#m03h').setAttribute('x2',cx);$('#m03h').setAttribute('y1',cy);$('#m03h').setAttribute('y2',cy);$('#m03v').setAttribute('x1',cx);$('#m03v').setAttribute('x2',cx);$('#m03v').setAttribute('y1',cy);$('#m03v').setAttribute('y2',380)};slider.oninput=update;update()}
  function lineSegment(a,slope,qMax=120,pMax=8){const pts=[];[[0,a],[pMax,a+slope*pMax]].forEach(([p,q])=>{if(q>=0&&q<=qMax)pts.push({p,q})});[[0,(0-a)/slope],[qMax,(qMax-a)/slope]].forEach(([q,p])=>{if(p>=0&&p<=pMax)pts.push({p,q})});const u=[];pts.forEach(v=>{if(!u.some(z=>Math.abs(z.p-v.p)<1e-6&&Math.abs(z.q-v.q)<1e-6))u.push(v)});u.sort((a,b)=>a.p-b.p);return[u[0],u[u.length-1]]}
  function renderModel04(){dom.modelTitle.textContent='需求、供給與市場均衡';dom.modelIntro.textContent='價格點永遠由目前生效中的需求與供給方程式重算。曲線位移後再改價格，點不會留在舊線。';dom.modelVisual.innerHTML='<svg viewBox="0 0 720 440"><line class="axis" x1="70" y1="35" x2="70" y2="380"/><line class="axis" x1="70" y1="380" x2="670" y2="380"/><line class="curve-a curve-old" id="m04d0"/><line class="curve-a" id="m04d"/><line class="curve-b curve-old" id="m04s0"/><line class="curve-b" id="m04s"/><circle class="point" id="m04point" r="10"/><line class="guide" id="m04price"/><text class="chart-label" x="18" y="40">價格</text><text class="chart-label" x="560" y="425">數量</text></svg>';dom.modelControls.innerHTML='<div class="control-group"><label>目前價格 <output id="m04p">NT$5,000</output></label><input id="m04priceSlider" type="range" min=".5" max="7.5" value="5" step=".25"></div><div class="control-group"><label>需求衝擊 <output id="m04dShift">0</output></label><input id="m04dSlider" type="range" min="-20" max="25" value="0" step="5"></div><div class="control-group"><label>供給衝擊 <output id="m04sShift">0</output></label><input id="m04sSlider" type="range" min="-20" max="25" value="0" step="5"></div><div class="model-summary"><span>市場狀態</span><strong id="m04summary"></strong><p>需求量 Qd = 100 + shock − 10P；供給量 Qs = −10 + shock + 10P。</p></div>';const X=q=>70+q/120*600,Y=p=>380-p/8*345,setL=(id,seg)=>{const n=$(id);n.setAttribute('x1',X(seg[0].q));n.setAttribute('y1',Y(seg[0].p));n.setAttribute('x2',X(seg[1].q));n.setAttribute('y2',Y(seg[1].p))};const update=()=>{const p=Number($('#m04priceSlider').value),ds=Number($('#m04dSlider').value),ss=Number($('#m04sSlider').value),qd=100+ds-10*p,qs=-10+ss+10*p;$('#m04p').textContent='NT$'+Math.round(p*1000).toLocaleString('zh-TW');$('#m04dShift').textContent=(ds>0?'+':'')+ds;$('#m04sShift').textContent=(ss>0?'+':'')+ss;setL('#m04d0',lineSegment(100,-10));setL('#m04d',lineSegment(100+ds,-10));setL('#m04s0',lineSegment(-10,10));setL('#m04s',lineSegment(-10+ss,10));$('#m04point').setAttribute('cx',X(qd));$('#m04point').setAttribute('cy',Y(p));$('#m04price').setAttribute('x1',70);$('#m04price').setAttribute('x2',X(qd));$('#m04price').setAttribute('y1',Y(p));$('#m04price').setAttribute('y2',Y(p));const gap=Math.round((qd-qs)*1000);$('#m04summary').textContent=Math.abs(gap)<1000?'市場接近均衡。':gap>0?`短缺 ${gap.toLocaleString('zh-TW')} 張，價格有上升壓力。`:`過剩 ${(-gap).toLocaleString('zh-TW')} 張，價格有下降壓力。`};['#m04priceSlider','#m04dSlider','#m04sSlider'].forEach(id=>$(id).oninput=update);update()}
  function renderModel19(){dom.modelTitle.textContent='AD–AS 衝擊與政策兩難';dom.modelIntro.textContent='同時調整總合需求與短期總合供給，觀察實質 GDP、物價與產出缺口。';dom.modelVisual.innerHTML='<svg viewBox="0 0 720 440"><line class="axis" x1="70" y1="35" x2="70" y2="380"/><line class="axis" x1="70" y1="380" x2="670" y2="380"/><line class="guide" x1="570" y1="35" x2="570" y2="380"/><line class="curve-a curve-old" id="m19ad0"/><line class="curve-a" id="m19ad"/><line class="curve-b curve-old" id="m19as0"/><line class="curve-b" id="m19as"/><circle class="point" id="m19point" r="10"/><line class="guide" id="m19h"/><line class="guide" id="m19v"/><text class="chart-label" x="18" y="40">物價</text><text class="chart-label" x="535" y="425">實質 GDP</text></svg>';dom.modelControls.innerHTML='<div class="control-group"><label>AD 衝擊 <output id="m19adShift">0</output></label><input id="m19adSlider" type="range" min="-25" max="25" value="0" step="5"></div><div class="control-group"><label>SRAS 衝擊 <output id="m19asShift">0</output></label><input id="m19asSlider" type="range" min="-25" max="25" value="0" step="5"></div><div class="model-summary"><span>新均衡</span><strong id="m19summary"></strong><p>負向供給衝擊會使物價上升、產出下降；需求刺激可支撐產出，但也可能加重通膨。</p></div>';const X=q=>70+q/120*600,Y=p=>380-p/8*345,setL=(id,seg)=>{const n=$(id);n.setAttribute('x1',X(seg[0].q));n.setAttribute('y1',Y(seg[0].p));n.setAttribute('x2',X(seg[1].q));n.setAttribute('y2',Y(seg[1].p))};const update=()=>{const ds=Number($('#m19adSlider').value),ss=Number($('#m19asSlider').value),p=(120+ds-ss)/25,q=110+ds-10*p;$('#m19adShift').textContent=(ds>0?'+':'')+ds;$('#m19asShift').textContent=(ss>0?'+':'')+ss;setL('#m19ad0',lineSegment(110,-10));setL('#m19ad',lineSegment(110+ds,-10));setL('#m19as0',lineSegment(-10,15));setL('#m19as',lineSegment(-10+ss,15));$('#m19point').setAttribute('cx',X(q));$('#m19point').setAttribute('cy',Y(p));$('#m19h').setAttribute('x1',70);$('#m19h').setAttribute('x2',X(q));$('#m19h').setAttribute('y1',Y(p));$('#m19h').setAttribute('y2',Y(p));$('#m19v').setAttribute('x1',X(q));$('#m19v').setAttribute('x2',X(q));$('#m19v').setAttribute('y1',Y(p));$('#m19v').setAttribute('y2',380);const gap=q-100;$('#m19summary').textContent=`實質 GDP 約 ${q.toFixed(1)}；物價水準約 ${p.toFixed(1)}；${gap>0?'正產出缺口':gap<0?'負產出缺口':'接近潛在 GDP'}。`};['#m19adSlider','#m19asSlider'].forEach(id=>$(id).oninput=update);update()}
  function renderPractice(){const bank=current()[state.practice];dom.practice.innerHTML=bank.map((item,i)=>`<article class="question-card" data-q="${i}"><span class="q-index">${state.practice==='quick'?'快速':'綜合'} ${String(i+1).padStart(2,'0')}</span><h3>${item.q}</h3><div class="options">${item.options.map((o,j)=>`<button data-answer="${i}-${j}">${o}</button>`).join('')}</div><div class="feedback">${item.why||'請回到模型，說明造成曲線或結果改變的原因。'}</div></article>`).join('');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const [qi,oi]=b.dataset.answer.split('-').map(Number),item=bank[qi];b.parentElement.querySelectorAll('button').forEach((x,j)=>{x.classList.toggle('correct',j===item.answer);x.classList.toggle('wrong',j===oi&&j!==item.answer)});b.closest('.question-card').querySelector('.feedback').classList.add('show');state.answers[`${state.chapter}-${state.practice}-${qi}`]=oi})}
  function renderAll(){setTheme();renderTabs();renderHero();renderBook();renderModel();renderPractice()}
  window.addEventListener('message',e=>{const d=e.data||{};if(d.type==='econ-animation-ready'){animationDuration=d.duration||current().duration}if(d.type==='econ-animation-time'){currentAnimationTime=d.time||0;const seek=window.__activeSeek,readout=window.__activeReadout;if(seek){seek.max=d.duration;seek.value=d.time}if(readout)readout.textContent=`${fmt(d.time)} / ${fmt(d.duration)}`}});
  dom.prev.onclick=()=>{if(state.page>0){state.page--;renderBook()}};dom.next.onclick=()=>{if(state.page<current().pages.length-1){state.page++;renderBook()}};$('#showQuick').onclick=()=>{state.practice='quick';renderPractice()};$('#showFinal').onclick=()=>{state.practice='final';renderPractice()};$('#resetPractice').onclick=()=>{state.answers={};renderPractice()};$('#restartAnimation').onclick=()=>{const start=pageAnimationStart(state.page);animationFrame?.contentWindow.postMessage({type:'econ-animation-seek',time:start},'*');animationFrame?.contentWindow.postMessage({type:'econ-animation-play'},'*')};$('#teacherMode').onclick=()=>{state.teacher=!state.teacher;document.body.classList.toggle('teacher-mode',state.teacher);$('#teacherMode').textContent=state.teacher?'離開教師模式':'教師模式'};$('#chapterMenu').onclick=()=>dom.dialog.showModal();$('#closeDialog').onclick=()=>dom.dialog.close();
  renderAll();
})();
